baseurl = "https://s.ragavan.co/"
title = "Ruminations"
theme = "ghostwriter"
languageCode = "en-us"
copyright = "Shreyas Ragavan"
#disqusShortname = "XXX"
#googleAnalytics = "XXX"

[Privacy]

[Privacy.disqus]
    disable = true

[Privacy.googleAnalytics]
    anonymizeIP = true
    respectDoNotTrack = true
    useSessionStorage = false

[Author]
    name = "Shreyas"
    profile = "https://google.com/+XXX"
    email = "sr@eml.cc"
    nick = "shrysr"

[Taxonomies]
    tag = "tags"

[Params]
    intro = true
    headline = "Ruminations"
    description = "Blog | Notes | Projects  -- My virtual palace"
    github = "https://github.com/shrysr"
    #gitlab = "https://gitlab.com/XXX"
    linkedin = "https://linkedin.com/in/shreyasragavan/"
    #gplus = "https://google.com/+XXX"
    twitter = "https://twitter.com/shreyasragavan"
    #@stackoverflow = "https://stackoverflow.com/users/XXX/YYY"
    #microblog = "https://micro.blog/XXX"
    feedurl = "http://example.com/index.xml"
    webmentionEndpoint = "https://example.com/webmention"
    pingbackEndpoint = "https://example.com/pingback"
    micropubEndpoint = "https://example.com/webmention/micropub"
    email = "sr@eml.cc"
    opengraph = true
    shareTwitter = true
    shareFacebook = false
    shareGooglePlus = true
    shareLinkedIn = true
    dateFormat = "Mon, Jan 2, 2006"
    highlightJsUrl = ""
    highlightJsLocalUrl = ""

[Permalinks]
    post = "/:year/:month/:day/:filename/"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Projects"
    url = "/project/"
    weight = 2

[[menu.main]]
    name = "Contact"
    url = "/page/connect/"
    weight = 3

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 4
